# Generated by Django 4.2.27 on 2025-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['book_id'], 'verbose_name': '图书', 'verbose_name_plural': '图书管理'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='书籍ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category_level1',
            field=models.CharField(default='', max_length=50, verbose_name='一级分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category_level2',
            field=models.CharField(default='', max_length=50, verbose_name='二级分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=100, verbose_name='出版社'),
            preserve_default=False,
        ),
    ]
