# Generated by Django 4.2.27 on 2025-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_options_remove_book_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_count',
            field=models.IntegerField(default=0, verbose_name='借阅次数'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='评分'),
        ),
    ]
